/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserWithVacationRequestDetailsDto } from '../../models/user-with-vacation-request-details-dto';

export interface GetAllEmployeesWithVacationRequests$Params {
}

export function getAllEmployeesWithVacationRequests(http: HttpClient, rootUrl: string, params?: GetAllEmployeesWithVacationRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserWithVacationRequestDetailsDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllEmployeesWithVacationRequests.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserWithVacationRequestDetailsDto>>;
    })
  );
}

getAllEmployeesWithVacationRequests.PATH = '/vacation-request/get-employees-with-vacation-requests';
