/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserWithWorkingDaysDetailsDto } from '../../models/user-with-working-days-details-dto';

export interface GetEmployeesWithWorkingDays$Params {
}

export function getEmployeesWithWorkingDays(http: HttpClient, rootUrl: string, params?: GetEmployeesWithWorkingDays$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserWithWorkingDaysDetailsDto>>> {
  const rb = new RequestBuilder(rootUrl, getEmployeesWithWorkingDays.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserWithWorkingDaysDetailsDto>>;
    })
  );
}

getEmployeesWithWorkingDays.PATH = '/working-days/get-employees-with-working-days';
