/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyDto } from '../models/company-dto';
import { RegistrationRequest } from '../models/registration-request';
export interface CompanyWithAdminsDto {
  adminRegistrations?: Array<RegistrationRequest>;
  companyDTO: CompanyDto;
}
