/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyDto {
  address?: string;
  companyId?: number;
  name?: string;
  telefonNumber?: string;
}
