/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyDto } from '../models/company-dto';
import { UserDetailsDto } from '../models/user-details-dto';
export interface CompanyDetailsDto {
  admins?: Array<UserDetailsDto>;
  companyDTO: CompanyDto;
}
