/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Contract } from '../models/contract';
export interface Company {
  address: string;
  contracts?: Array<Contract>;
  id?: number;
  name: string;
  telefonNumber: string;
}
