/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { User } from '../models/user';
export interface Contract {
  actualYearVacationDays?: number;
  company?: Company;
  idContract?: number;
  previousYearVacationDays?: number;
  signingDate?: string;
  user?: User;
}
