/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  email: string;
  firstName: string;
  lastName: string;
  passwordHash: string;
  signingDate?: string;
  telefonNumber?: string;
}
