/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Contract } from '../models/contract';
import { GrantedAuthority } from '../models/granted-authority';
import { VacationRequest } from '../models/vacation-request';
import { WorkingDay } from '../models/working-day';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  contract?: Contract;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  id?: number;
  lastName?: string;
  managedRequests?: Array<VacationRequest>;
  name?: string;
  password?: string;
  passwordHash?: string;
  role?: 'Superadmin' | 'Administrator' | 'Employee';
  telefonNumber?: string;
  username?: string;
  vacationRequests?: Array<VacationRequest>;
  workingDays?: Array<WorkingDay>;
}
