/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDetailsDto {
  accountLocked?: boolean;
  actualYearVacationDays?: number;
  companyName?: string;
  email: string;
  firstName?: string;
  fullName?: string;
  id?: number;
  lastName?: string;
  role?: 'Superadmin' | 'Administrator' | 'Employee';
  signingDate?: string;
  telefonNumber?: string;
}
