/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDetailsDto } from '../models/user-details-dto';
import { WorkingDaysDto } from '../models/working-days-dto';
export interface UserWithWorkingDaysDetailsDto {
  userDetailsDTO: UserDetailsDto;
  workingDays?: Array<WorkingDaysDto>;
}
