/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserWithCompanyDto {
  accountLocked?: boolean;
  companyName?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  role?: 'Superadmin' | 'Administrator' | 'Employee';
  telefonNumber?: string;
}
