/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  first_name?: string;
  id?: number;
  last_name?: string;
  name?: string;
  password?: string;
  password_hash?: string;
  role?: 'Superadmin' | 'Administrator' | 'Employee';
  username?: string;
}
