/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDetailsDto } from '../models/user-details-dto';
import { VacationRequestDetailsDto } from '../models/vacation-request-details-dto';
export interface UserWithVacationRequestDetailsDto {
  userDetailsDTO: UserDetailsDto;
  vacationRequests?: Array<VacationRequestDetailsDto>;
}
