/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VacationRequestDto {
  assignedAdministratorId?: number;
  description?: string;
  endDate?: string;
  startDate?: string;
}
