/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VacationRequestDetailsDto {
  adminEmail?: string;
  description?: string;
  employeeEmail?: string;
  employeeFullName?: string;
  employeeId?: number;
  endDate?: string;
  id?: number;
  requestedDate?: string;
  startDate?: string;
  status?: 'New' | 'Approved' | 'Rejected';
  vacationDays?: number;
}
