/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface WorkingDay {
  date: string;
  description: string;
  employee: User;
  endDate: string;
  id?: number;
  startDate: string;
}
