/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkingDaysDto {
  date?: string;
  description?: string;
  effectiveHours?: number;
  effectiveTime?: string;
  endDate?: string;
  id?: number;
  startDate?: string;
}
