spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Unternehmensplattform?createDatabaseIfNotExist=true
    username: dev
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql

#spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.generate-ddl=true


application:
  security:
    jwt:
      secret-key: 7506d035980f7bee4108beb06780ed76ea48ee6abd43abd5ed9fef8f1ca03e99
      expiration: 1800000
#      expiration: 8640000
