/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { WorkingDaysControllerService } from './services/working-days-controller.service';
export { VacationReqControllerService } from './services/vacation-req-controller.service';
export { UserCrudControllerService } from './services/user-crud-controller.service';
export { CompanyControllerService } from './services/company-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
